### ISSUE TITLE
Support for uwp

### ISSUE THREAD

**Issue by soumyamahunt** [cyanfish/grpc-dotnet-namedpipes#10]
Does this support uwp app as client like grpc does?? If not it would be better to indicate in readme.

**Comment by cyanfish** [comment]
I'm not sure how well UWP supports named pipes, though [this article](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getnamedpipeclientsessionid#remarks) has some information that may be helpful.

**Comment by soumyamahunt** [comment]
> I'm not sure how well UWP supports named pipes, though [this article](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getnamedpipeclientsessionid#remarks) has some information that may be helpful.

I am getting error while trying to communicate between uwp and a win32 app. I used [this](https://github.com/hannesne/NamedPipesSample) project as reference for win32 app as server and uwp app as client. The exception occurs with message "`Access to the path is denied.`".
The full stack trace:
```
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at GrpcDotNetNamedPipes.Internal.ClientConnectionContext.InitCall[TRequest,TResponse](Method`2 method, TRequest request)
   at GrpcDotNetNamedPipes.NamedPipeChannel.CreateConnectionContext[TRequest,TResponse](Method`2 method, CallOptions callOptions, TRequest request)
   at GrpcDotNetNamedPipes.NamedPipeChannel.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions callOptions, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Notepads.DesktopExtension.AdminCommands.AdminCommandsClient.SaveFileAsync(FileWriteRequest request, CallOptions options) in B:\GitRepos\Notepads\src\Notepads.DesktopExtension\Generated\AdminGrpc.cs:line 116
   at Notepads.DesktopExtension.AdminCommands.AdminCommandsClient.SaveFileAsync(FileWriteRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in B:\GitRepos\Notepads\src\Notepads.DesktopExtension\Generated\AdminGrpc.cs:line 106
   at Notepads.Services.DesktopExtensionService.<SaveFileAsAdmin>d__10.MoveNext() in B:\GitRepos\Notepads\src\Notepads\Services\DesktopExtensionService.cs:line 88
```
