### ISSUE TITLE
Getting: System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by maddinthegreat** [cyanfish/grpc-dotnet-namedpipes#15]
System.NotImplementedException: The method or operation is not implemented.
   at Grpc.Core.Marshaller`1.<>c.<.ctor>b__5_0(T msg)
   at GrpcDotNetNamedPipes.Internal.ClientConnectionContext.InitCall[TRequest,TResponse](Method`2 method, TRequest request)
   at GrpcDotNetNamedPipes.NamedPipeChannel.CreateConnectionContext[TRequest,TResponse](Method`2 method, CallOptions callOptions, TRequest request)
   at GrpcDotNetNamedPipes.NamedPipeChannel.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions callOptions, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at gRPCPipeClient.Greeter.GreeterClient.SayHelloAsync(HelloRequest request, CallOptions options)

Example projects:
https://wawiproapps-my.sharepoint.com/:f:/g/personal/info_wawi-proapp_de/EmVTEfuOXr1LqZTYUng0zSUBrPclSySPE-AiCe2j57FzOw?e=ZetAKD

**Comment by maddinthegreat** [comment]
[Code]()https://wawiproapps-my.sharepoint.com/:f:/g/personal/info_wawi-proapp_de/EmVTEfuOXr1LqZTYUng0zSUBrPclSySPE-AiCe2j57FzOw?e=ZetAKD

**Comment by Arvidas** [comment]
Upgraded packages brake it:
https://github.com/cyanfish/grpc-dotnet-namedpipes/issues/13

**Comment by cyanfish** [comment]
Fixed in version 1.2.0.
