### ISSUE TITLE
System.UnauthorizedAccessException when contacting gRPC server from another user

### ISSUE THREAD

**Issue by LAB02-Admin** [cyanfish/grpc-dotnet-namedpipes#38]
Hi again,

I'm running a service under SYSTEM account, and want to contact it from a normal user. I've already set `CurrentUserOnly = false` in both the client and server, but I still get a `System.UnauthorizedAccessException` whenever I try to connect.

If I run my client application elevated, it works fine, but that's not an option for deployment. 

I don't see any options to set the security options like [in this thread](https://stackoverflow.com/questions/3478166/named-pipe-server-throws-unauthorizedaccessexception-when-creating-a-second-inst), 

I'm guessing that has to do with the fact that I'm using .NET 6. In the past I've used this library [NamedPipeServerStream.NetFrameworkVersion](NamedPipeServerStream.NetFrameworkVersion) to restore the security options from .NET Framework. Is that something that could be used here?

**Comment by LAB02-Admin** [comment]
Update: I enabled PipeSecurity by adding NET6_0 to `NamedPipeServerOptions.cs` in your library:

```C#
#if NETFRAMEWORK || NET5_0 || NET6_0
        /// <summary>
        /// Gets or sets a value indicating the access control to be used for the pipe.
        /// </summary>
        public PipeSecurity PipeSecurity { get; set; }
#endif
```

Also added `net6.0-windows` as a target framework. I can make a PR if you want.

However, the problem's still there. I initialize the server with these settings (took them from `GrpcNamedPipeTests.cs` -> `SimpleUnaryWithACLs()`:

```C#
var pipeSecurity = new PipeSecurity();
var usersSid = new SecurityIdentifier(WellKnownSidType.WorldSid, null);
var systemSid = new SecurityIdentifier(WellKnownSidType.LocalSystemSid, null);
pipeSecurity.AddAccessRule(new PipeAccessRule(usersSid, PipeAccessRights.ReadWrite, AccessControlType.Allow));
pipeSecurity.AddAccessRule(new PipeAccessRule(systemSid, PipeAccessRights.FullControl, AccessControlType.Allow));

var serverOptions = new NamedPipeServerOptions
{
    PipeSecurity = pipeSecurity
};
```

Tried with `CurrentUserOnly = false` as well. The service runs as `SYSTEM`, the client as a normal user. 

I initialize the client's channel as such:

```C#
private readonly NamedPipeChannel _serviceChannel = new(".", Variables.PipeName, new NamedPipeChannelOptions 
{ 
        ConnectionTimeout = (int)TimeSpan.FromSeconds(10).TotalMilliseconds
});
```

Tried a bunch of `TokenImpersonationLevel` types as well, and `CurrentUserOnly = false` - no luck.

Any idea what I'm missing or doing wrong? Thanks!

**Comment by LAB02-Admin** [comment]
Here are the full exception log entries (client side, no entries in the server's log):


```
2022-03-16 11:30:35.905 +01:00 [FTL] [PROGRAM] FirstChanceException: Access to the path is denied.
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at GrpcDotNetNamedPipes.Internal.ClientConnectionContext.InitCall[TRequest,TResponse](Method`2 method, TRequest request)
   at GrpcDotNetNamedPipes.NamedPipeChannel.CreateConnectionContext[TRequest,TResponse](Method`2 method, CallOptions callOptions, TRequest request)
```

```
2022-03-16 11:31:24.289 +01:00 [FTL] [PROGRAM] FirstChanceException: Access to the path is denied.
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at GrpcDotNetNamedPipes.Internal.ClientConnectionContext.InitCall[TRequest,TResponse](Method`2 method, TRequest request)
   at GrpcDotNetNamedPipes.NamedPipeChannel.CreateConnectionContext[TRequest,TResponse](Method`2 method, CallOptions callOptions, TRequest request)
   at GrpcDotNetNamedPipes.NamedPipeChannel.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions callOptions, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at HassAgentSatelliteRpcCalls.HassAgentSatelliteRpcCallsClient.PingAsync(PingRequest request, CallOptions options) in F:\...\Service\Protos\HassagentsatelliteGrpc.cs:line 241
   at HassAgentSatelliteRpcCalls.HassAgentSatelliteRpcCallsClient.PingAsync(PingRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in F:\...\Service\Protos\HassagentsatelliteGrpc.cs:line 236
   at HASSAgent.Service.RpcClientService.PingAsync() in F:\...\Service\RpcClientService.cs:line 29
   at HASSAgent.Controls.Service.General.<>c.<<InitializeService>b__2_0>d.MoveNext() in F:\...\Controls\Service\General.cs:line 50
--- End of stack trace from previous location ---
   at HASSAgent.Controls.Service.General.InitializeService() in F:\...\Controls\Service\General.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

**Comment by LAB02-Admin** [comment]
Okay, I fixed it. Had to add `NET6_0` to `ServerStreamPool.cs` as well:

```C#
#if NET5_0 || NET6_0
            return NamedPipeServerStreamAcl.Create(_pipeName,
                PipeDirection.InOut,
                NamedPipeServerStream.MaxAllowedServerInstances,
                PipeTransmissionMode.Message,
                pipeOptions,
                0,
                0,
                _options.PipeSecurity);
#else
            return new NamedPipeServerStream(_pipeName,
                PipeDirection.InOut,
                NamedPipeServerStream.MaxAllowedServerInstances,
                PipeTransmissionMode.Message,
                pipeOptions);
#endif
```

Let me know if you want me to make a PR for this, if it's the solution you'd recommend.

**Comment by cyanfish** [comment]
Hi, thanks for figuring that out! I'd merge a PR that uses NET5_0_OR_GREATER instead of NET5_0.

**Comment by LAB02-Admin** [comment]
Hey @cyanfish, could you please take a look at the PR and possible merge it? I now compiled and added my own library and its dependencies, but it'd be cleaner if I could just add your package again :)

Thanks!

**Comment by cyanfish** [comment]
Sorry I didn't get to this until now, but this should be in 2.0.0 (along with some other changes listed in the changelog).
